spring.datasource.url=jdbc:h2:mem:postsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.profiles.active=dev

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:dev-data.sql

cors.allowed-origin=http://localhost
cors.allowed-methods=POST,PUT,GET,OPTIONS,DELETE
cors.allowed-headers=*
cors.allow-credentials=true

spring.servlet.multipart.max-file-size=5242880
spring.servlet.multipart.max-request-size=20971520